config/routes.rb
Fmmc::Application.routes.draw do

=begin
  resources :clients, only: [:index, :show, :destroy]
  resources :messages, only: [:index, :show]
  resources :feedbacks, only: [:index, :show]
  resources :chats, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :offers, only: [:index, :show]
  resources :templates

  root to: 'static_pages#home'

  mount Mobile::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'
=end

  mount Fmmc::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq_username && password == Settings.sidekiq_password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  require 'sidekiq/api'
  match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }
  match "queue-latency" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.latency < 30 ? "OK" : "UHOH" ]] }

end

app/models/message.rb
class Message < BaseMessage
  belongs_to :template

  attr_accessible :click_action, :content, :user_id, :message_type, :template, :status

  def self.unread_num(user_id)
    where(
        "user_id = :user_id and status = :status",
        user_id: user_id,
        status: Constants::Status::UNREAD
    ).count
  end

  def to_id
    user_id
  end

  def to_mobile_phone
    client = Client.find_by_user_id(user_id)
    client.mobile_phone
  end

  def update_push_result(response)
    update_attributes(  push_error_code: response['result'],
                        push_error_msg: response['status'],
                        push_result: response['result'] == 'ok' ? 1 : 0,
                        pushed_at: Time.now)
  end

  def update_sms_result(response)
    update_attributes(  sms_error_code: response['messages'][0]['status'],
                        sms_error_msg: response['messages'][0]['error-text'],
                        sms_result: response['messages'][0]['status'] == '0' ? 1 : 0,
                        sms_sent_at: Time.now)
  end

  def push_alert
    content
  end

  # 合成push透传内容
  def push_payload
    { type: 'S', text: content}.to_json
  end

  # 合成push透传内容
  def push_payload_ios
    { type: 'S' }.to_json
  end

  def mark_read
    update_attributes(
        status: Constants::Status::READ
    )
  end

  def mark_deleted
    update_attributes(
        status: Constants::Status::DELETED
    )
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # GET /messages
  # GET /messages.json
  def index
    @pushes = initialize_grid(
        Push,
        :conditions => { pushable_type: 'Message'},
        :order => 'id',
        :order_direction => 'DESC'
    )
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @push = Push.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @push }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<% provide(:title, 'All messages') %>
<h1>All messages</h1>

  <%= grid(@pushes, upper_pagination_panel: true, allow_showing_all_records:  false) do |g|

    g.row_attributes do |push|
      if push.status == Constants::PushStatus::FAILURE
        {:class => 'danger'}
      end
    end

    g.column name:  'Message ID', attribute: 'id', model: 'Message' do |push|
      push.pushable.id
    end

    g.column name:  'Push ID' do |push|
      push.id
    end

    g.column name:  'User ID', attribute: 'user_id', model: 'Client'  do |push|
      link_to(push.client.user_id, client_path(push.client.id))
    end

    g.column  name:  'Content', attribute: 'content', model: 'Message' do |push|
      push.pushable.content
    end

    g.column  name:  'Template' do |push|
      push.pushable.template.name
    end

    g.column  name:  'Push status', attribute: 'status', custom_filter: Constants::PushStatus::KEY_MAP, ordering: false, allow_multiple_selection: false do |push|
       push_status(push.status)
    end

    g.column name:  'Pushed' do |push|
      push.pushed_at ? push.pushed_at.to_s(:short) : ''
    end

    g.column name:  'Added' do |push|
      push.pushable.created_at.to_s(:short)
    end

    g.column name:  'Updated' do |push|
      push.pushable.updated_at.to_s(:short)
    end

    g.column do |push|
      link_to('View', message_path(push), class: 'btn btn-info')
    end
  end -%>

app/views/messages/show.html.erb
<% provide(:title, "Push##{@push.id}") %>

<p>
  <b>Message ID:</b>
  <%= @push.pushable.id %>
</p>

<p>
  <b>Push ID:</b>
  <%= @push.id %>
</p>

<p>
  <b>Content:</b>
  <%= @push.pushable.content %>
</p>

<p>
  <b>User ID:</b>
  <%= @push.pushable.user_id %>
</p>

<%= render 'layouts/push', object: @push %>

<p>
  <b>Status:</b>
  <%= message_status(@push) %>
</p>

<p>
  <b>Added:</b>
  <%= @push.created_at %>
</p>

<p>
  <b>Updated:</b>
  <%= @push.updated_at %>
</p>

<%= link_to 'Back', messages_path, class: 'btn btn-default' %>