config/routes.rb
Fmmc::Application.routes.draw do

=begin
  resources :clients, only: [:index, :show, :destroy]
  resources :messages, only: [:index, :show]
  resources :feedbacks, only: [:index, :show]
  resources :chats, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :offers, only: [:index, :show]
  resources :templates

  root to: 'static_pages#home'

  mount Mobile::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'
=end

  mount Fmmc::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq_username && password == Settings.sidekiq_password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  require 'sidekiq/api'
  match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }
  match "queue-latency" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.latency < 30 ? "OK" : "UHOH" ]] }

end

app/views/templates/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@template) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %><br />
        <%= f.text_field :name %>

        <%= f.label :message_type %><br />
        <%= f.select :message_type, message_types %>

        <%= f.label :content %><br />
        <%= f.text_area :content %>

        <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template, class: 'btn btn-default' %> |
<%= link_to 'Back', templates_path, class: 'btn btn-default' %>

app/views/templates/index.html.erb
<% provide(:title, 'All templates') %>
<h1>All templates</h1>
<p>
<%= link_to 'New Template', new_template_path, class: "btn btn-primary" %>
</p>

  <%= grid(@templates, upper_pagination_panel: true, allow_showing_all_records:  false) do |g|

    g.column name:  'ID' do |template|
      template.id
    end

    g.column name:  'Name', attribute: 'name'  do |template|
      template.name
    end

    g.column  name:  'Message type', attribute: 'message_type', custom_filter: message_types, allow_multiple_selection: false do |template|
      template.message_type
    end

    g.column  name:  'Content', attribute: 'content' do |template|
      template.content
    end

    g.column name:  'Added', attribute: 'created_at' do |template|
      template.created_at.to_s(:short)
    end

    g.column name:  'Updated', attribute: 'updated_at' do |template|
      template.updated_at.to_s(:short)
    end

    g.column do |template|
      link_to('Edit', edit_template_path(template), class: 'btn btn-primary')
    end

    g.column do |template|
      link_to('Delete', template, method: :delete, data: { confirm: 'You sure?' }, class: 'btn btn-danger')
    end
  end -%>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path, class: 'btn btn-default' %>

app/views/templates/show.html.erb
<% provide(:title, "Template##{@template.id}") %>

<p>
  <b>Name:</b>
  <%= @template.name %>
</p>

<p>
  <b>Content:</b>
  <%= @template.content %>
</p>

<p>
  <b>Type:</b>
  <%= @template.message_type %>
</p>

<p>
  <b>Added:</b>
  <%= @template.created_at %>
</p>

<p>
  <b>Updated:</b>
  <%= @template.updated_at %>
</p>

<%= link_to 'Edit', edit_template_path(@template), class: 'btn btn-default' %> |
<%= link_to 'Back', templates_path, class: 'btn btn-default' %>