config/routes.rb
Fmmc::Application.routes.draw do

=begin
  resources :clients, only: [:index, :show, :destroy]
  resources :messages, only: [:index, :show]
  resources :feedbacks, only: [:index, :show]
  resources :chats, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :offers, only: [:index, :show]
  resources :templates

  root to: 'static_pages#home'

  mount Mobile::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'
=end

  mount Fmmc::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq_username && password == Settings.sidekiq_password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  require 'sidekiq/api'
  match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }
  match "queue-latency" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.latency < 30 ? "OK" : "UHOH" ]] }

end

app/models/feedback.rb
class Feedback < BaseMessage
  attr_accessible :comment, :item_id, :item_image, :item_title,
                  :rate_num, :seller_head, :seller_id, :seller_nick, :buyer_head, :buyer_id, :buyer_nick,
                  :sell_side, :thread_id, :entry_id

  def self.find_recent_by_user_and_item(user_id, user_type, item_id)
    sql = user_sql_clause(user_id, user_type)
    sql = "#{sql} and item_id = '#{item_id}'"
    feedbacks = where(sql).limit(1).order('id DESC')
    if feedbacks.size > 0
      { :type => 'F',
        :rate_num => feedbacks[0].rate_num,
        :message => feedbacks[0].comment,
        :from_user_id => feedbacks[0].sell_side == Constants::SellSide::BUYER_TO_SELLER ? feedbacks[0].buyer_id : feedbacks[0].seller_id,
        :from_user_nick => feedbacks[0].sell_side == Constants::SellSide::BUYER_TO_SELLER ? feedbacks[0].buyer_nick : feedbacks[0].seller_nick,
        :thread_id => feedbacks[0].thread_id,
        :timestamp => feedbacks[0].created_at.to_i
      }
    else
      {}
    end
  end

  def self.unread_num(user_id, user_type, item_id = nil)
    sql = user_unread_sql_clause(user_id, user_type)
    if item_id
      sql = "#{sql} and item_id = '#{item_id}'"
    end
    where(sql).count
  end

  def to_id
    sell_side == 1 ? buyer_id : seller_id
  end

  def to_mobile_phone
    client = Client.find_by_user_id(to_id)
    client.mobile_phone
  end

  def update_push_result(response)
    update_attributes(  push_error_code: response['result'],
                        push_error_msg: response['status'],
                        push_result: response['result'] == 'ok' ? 1 : 0,
                        pushed_at: Time.now)
  end

  def update_sms_result(response)
    update_attributes(  sms_error_code: response['messages'][0]['status'],
                        sms_error_msg: response['messages'][0]['error-text'],
                        sms_result: response['messages'][0]['status'] == '0' ? 1 : 0,
                        sms_sent_at: Time.now)
  end

  def push_alert
    from = sell_side == 1 ? seller_nick : buyer_nick
    alert = "#{from} left you feedback: #{rate_num} points"
    if !comment.blank?
      alert = "#{alert}, #{comment}"
    end
    alert
  end

  # 合成push透传内容
  def push_payload
    from = sell_side == 1 ? seller_nick : buyer_nick
    { type: 'F', id: entry_id, thread: thread_id, from: from, rate: rate_num, comment: comment}.to_json
  end

  # 合成push透传内容
  def push_payload_ios
    { type: 'F', thread: thread_id }.to_json
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @pushes = initialize_grid(
        Push,
        :conditions => { pushable_type: 'Feedback'},
        :order => 'id',
        :order_direction => 'DESC'
    )
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @push = Push.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @push }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/index.html.erb
<% provide(:title, 'All feedbacks') %>
<h1>All feedbacks</h1>

  <%= grid(@pushes, upper_pagination_panel: true, allow_showing_all_records:  false) do |g|

    g.row_attributes do |push|
      if push.status == Constants::PushStatus::FAILURE
        {:class => 'danger'}
      end
    end

    g.column name:  'Feedback ID', attribute: 'id', model: 'Feedback' do |push|
      push.pushable.id
    end

    g.column name:  'Push ID' do |push|
      push.id
    end

    g.column name:  'Buyer ID', attribute: 'buyer_id', model: 'Feedback' do |push|
      content_tag(:span, push.pushable.buyer_id, { "data-toggle" => 'tooltip', "data-placement" => 'bottom', :title => push.pushable.buyer_nick })
    end

    g.column name:  'Buyer' do |push|
      head_image_tag(push.pushable.buyer_head, push.pushable.buyer_nick) unless push.pushable.buyer_head.blank?
    end

    g.column name:  ''  do |push|
      push.pushable.sell_side == 0 ? icon('arrow-right', '', class: 'fa-2x') : icon('arrow-left', '', class: 'fa-2x')
    end

    g.column name:  'Seller ID', attribute: 'seller_id', model: 'Feedback' do |push|
      content_tag(:span, push.pushable.seller_id, { "data-toggle" => 'tooltip', "data-placement" => 'bottom', :title => push.pushable.seller_nick })
    end

    g.column  name:  'Seller' do |push|
      head_image_tag(push.pushable.seller_head, push.pushable.seller_nick) unless push.pushable.seller_head.blank?
    end

    g.column  name:  'Rate number' do |push|
      content_tag(:i, icon('star') * push.pushable.rate_num, nil, false)
    end

    g.column  name:  'Comment' do |push|
      push.pushable.comment
    end

    g.column  name:  'Thread ID', attribute: 'thread_id', model: 'Feedback' do |push|
      push.pushable.thread_id
    end

    g.column  name:  'Entry ID', attribute: 'entry_id', model: 'Feedback' do |push|
      push.pushable.entry_id
    end

    g.column  name:  'Item title', attribute: 'item_title', model: 'Feedback' do |push|
      push.pushable.item_title
    end

    g.column  name:  'Push status', attribute: 'status', custom_filter: Constants::PushStatus::KEY_MAP, ordering: false, allow_multiple_selection: false do |push|
      push_status(push.status)
    end

    g.column name:  'Pushed' do |push|
      push.pushed_at ? push.pushed_at.to_s(:short) : ''
    end

    g.column name:  'Added' do |push|
      push.pushable.created_at.to_s(:short)
    end

    g.column name:  'Updated' do |push|
      push.pushable.updated_at.to_s(:short)
    end

    g.column do |push|
      link_to('View', feedback_path(push), class: 'btn btn-info')
    end
  end -%>

app/views/feedbacks/show.html.erb
<% provide(:title, "Push##{@push.id}") %>

<p>
  <b>Feedback ID:</b>
  <%= @push.pushable.id %>
</p>

<p>
  <b>Push ID:</b>
  <%= @push.id %>
</p>

<p>
  <b>Rate number:</b>
  <%= @push.pushable.rate_num %>
</p>

<p>
  <b>Comment:</b>
  <%= @push.pushable.comment %>
</p>

<p>
  <b>Sell side:</b>
  <%= @push.pushable.sell_side %>
</p>

<p>
  <b>Buyer ID:</b>
  <%= @push.pushable.buyer_id %>
</p>

<p>
  <b>Buyer nick:</b>
  <%= @push.pushable.buyer_nick %>
</p>

<p>
  <b>Buyer avatar:</b>
  <%= head_image_tag(@push.pushable.buyer_head, @push.pushable.buyer_nick) %>
</p>

<p>
  <b>Seller ID:</b>
  <%= @push.pushable.seller_id %>
</p>

<p>
  <b>Seller nick:</b>
  <%= @push.pushable.seller_nick %>
</p>

<p>
  <b>Seller avatar:</b>
  <%= head_image_tag(@push.pushable.seller_head, @push.pushable.seller_nick) %>
</p>

<p>
  <b>Thread ID:</b>
  <%= @push.pushable.thread_id %>
</p>

<p>
  <b>Entry ID:</b>
  <%= @push.pushable.entry_id %>
</p>

<p>
  <b>Item ID:</b>
  <%= @push.pushable.item_id %>
</p>

<p>
  <b>Item title:</b>
  <%= @push.pushable.item_title %>
</p>

<p>
  <b>Item image:</b>
  <%= item_image_tag(@push.pushable.item_image, @push.pushable.item_title) %>
</p>

<%= render 'layouts/push', object: @push %>

<p>
  <b>Status:</b>
  <%= message_status(@push.pushable) %>
</p>

<p>
  <b>Added:</b>
  <%= @push.created_at %>
</p>

<p>
  <b>Updated:</b>
  <%= @push.updated_at %>
</p>

<%= link_to 'Back', feedbacks_path, class: 'btn btn-default' %>