config/routes.rb
Fmmc::Application.routes.draw do

=begin
  resources :clients, only: [:index, :show, :destroy]
  resources :messages, only: [:index, :show]
  resources :feedbacks, only: [:index, :show]
  resources :chats, only: [:index, :show]
  resources :questions, only: [:index, :show]
  resources :offers, only: [:index, :show]
  resources :templates

  root to: 'static_pages#home'

  mount Mobile::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'
=end

  mount Fmmc::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc', :as => 'apidoc'

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq_username && password == Settings.sidekiq_password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  require 'sidekiq/api'
  match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }
  match "queue-latency" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.latency < 30 ? "OK" : "UHOH" ]] }

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Powered by  <a href="mailto:longzhi@wespoke.com">Dragon</a>
  </small>
  <!--<nav>-->
    <!--<ul>-->
      <!--<li><a href="http://news.5milesapp.com/">News</a></li>-->
    <!--</ul>-->
  <!--</nav>-->
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FMMC", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to icon('home', 'Home'), root_path %></li>
          <li><%= link_to icon('tasks', 'sidekiq'), sidekiq_web_path %></li>
          <li><%= link_to icon('mobile-phone', 'Clients'), clients_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= icon('wechat', 'Messages')%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Questions", questions_path %></li>
              <li><%= link_to "Offers", offers_path %></li>
              <li><%= link_to "Chats", chats_path %></li>
              <li><%= link_to "Feedbacks", feedbacks_path %></li>
              <li><%= link_to "Messages", messages_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Templates", templates_path %>
              </li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to icon('lightbulb-o', 'API'), apidoc_path %></li>
        </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div>

app/views/layouts/_push.html.erb
<p>
  <b>Client:</b>
  <%= link_to(object.client_id, client_path(object.client_id)) %>
</p>

<p>
  <b>Push status:</b>
  <%= Constants::PushStatus::VALUE_MAP[object.status] %>
</p>

<p>
  <b>error code:</b>
  <%= object.error_code %>
</p>

<p>
  <b>error message:</b>
  <%= object.error_msg %>
</p>

<p>
  <b>Pushed:</b>
  <%= object.pushed_at %>
</p>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag 'logo.png' %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert <%= bootstrap_class_for("#{key}") %> fade in">
        <button class="close" data-dismiss="alert">×</button>
        <%= value %>
      </div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>